@AddMember_HostAddress = http://localhost:5047
@Docker_HostAddress = http://localhost:8080

POST {{AddMember_HostAddress}}/addmember?name=test&lastname=test&birthyear=2020
Content-Type: application/json
Accept: application/json
###
POST {{Docker_HostAddress}}/addmember?name=test&lastname=test&birthyear=2020
Content-Type: application/json
Accept: application/json