@GetAdultById_HostAddress = http://localhost:5291

@Docker_HostAddress = http://localhost:5001

GET {{GetAdultById_HostAddress}}/Adult/{id}
Accept: application/json

###
GET {{Docker_HostAddress}}/Adult/2
Accept: application/json